### ISSUE TITLE
[ISSUE] Permissions for PRs

### ISSUE THREAD

**Issue by mihaituhari** [macmotp/locale#2]
Hi @macmotp 

I checked out the project on my local, created a new branch and tried to push it (in order to create a PR) but it seems like I don't have permissions.

Can you please check the contribution settings of the repository?
Thanks

**Comment by macmotp** [comment]
Hi @mihaituhari, this is an open source project. If you need to create a PR you need to fork the repository. You can follow these steps: https://github.com/gabrieldemarmiesse/getting_started_open_source.

Thanks!
